# Generated by Django 3.0.5 on 2020-05-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200502_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_events',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='users.Event'),
        ),
    ]
