# Generated by Django 3.0.5 on 2020-05-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_profile_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.CharField(default='unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(default='unknown', max_length=150),
        ),
    ]
